# Generated by Django 4.0.4 on 2022-05-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_excel_file', models.FileField(blank=True, null=True, upload_to='sample/')),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='sample/')),
                ('end_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('now_buistatus', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
    ]
