# Generated by Django 4.0.4 on 2022-05-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmanage',
            name='theme_status',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
