# Generated by Django 4.0.4 on 2022-05-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='today_divdb',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
