# Generated by Django 4.0.4 on 2022-05-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_alter_user_today_divdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='today_divdb',
        ),
    ]
