# Generated by Django 4.0.4 on 2022-05-22 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChkDbReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_dbreset', models.CharField(max_length=15)),
                ('chk_dbtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DbSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_status', models.CharField(blank=True, max_length=255, null=True)),
                ('ds_statusbase', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='setimage/')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('theme_status', models.CharField(choices=[('light', '라이트'), ('dark', '다크')], default='dark', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_company', models.CharField(max_length=30)),
                ('mk_name', models.CharField(max_length=10, null=True)),
                ('mk_phone', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')])),
                ('mk_advtype', models.CharField(choices=[('cpa', 'CPA'), ('cpc', 'CPC'), ('cps', 'CPS'), ('cpv', 'CPV'), ('cpm', 'CPM')], default='cpa', max_length=5, null=True)),
                ('mk_url', models.CharField(max_length=255, null=True)),
                ('mk_memo', models.TextField(null=True)),
                ('mk_status', models.CharField(choices=[('Y', '거래'), ('N', '미거래')], default='Y', max_length=5)),
                ('mk_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadDbName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbn_name', models.CharField(max_length=255)),
                ('dbn_price', models.IntegerField()),
                ('dbn_memo', models.CharField(max_length=255, null=True)),
                ('dbn_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('dbn_mkname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mkdname', to='dbmanageapp.marketinglist')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_phone', models.CharField(max_length=20)),
                ('db_member', models.CharField(max_length=20)),
                ('db_age', models.CharField(default='', max_length=20, null=True)),
                ('db_sex', models.CharField(default='', max_length=20, null=True)),
                ('db_inv', models.CharField(default='', max_length=20, null=True)),
                ('db_manager', models.CharField(max_length=20, null=True)),
                ('db_manager_nick', models.CharField(max_length=20, null=True)),
                ('db_status', models.CharField(default='', max_length=20, null=True)),
                ('db_paidprice', models.IntegerField(blank=True, default='0', null=True)),
                ('db_paidstatus', models.CharField(default='N', max_length=5, null=True)),
                ('db_lastpaiddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('db_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('db_mkname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbmkname', to='dbmanageapp.marketinglist')),
                ('db_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbname', to='dbmanageapp.uploaddbname')),
            ],
        ),
        migrations.CreateModel(
            name='TestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_name', models.CharField(max_length=15)),
                ('td_mkname', models.ManyToManyField(related_name='testfield', to='dbmanageapp.marketinglist')),
            ],
        ),
        migrations.CreateModel(
            name='PaidList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_paidprice', models.IntegerField(default='0')),
                ('pl_paiddate', models.DateTimeField(auto_now_add=True)),
                ('pl_chkdb', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plchkdb', to='dbmanageapp.uploaddb')),
            ],
        ),
        migrations.CreateModel(
            name='DbMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_memos', models.CharField(default='', max_length=2550)),
                ('dm_date', models.DateTimeField(auto_now_add=True)),
                ('dm_chkdb', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dmchkdb', to='dbmanageapp.uploaddb')),
            ],
        ),
    ]
