# Generated by Django 4.0.4 on 2022-06-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmemo',
            name='dm_mamager',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
