# Generated by Django 4.0.4 on 2022-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddb',
            name='de_seq',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
