# Generated by Django 4.0.4 on 2022-05-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0002_alter_uploaddb_de_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddb',
            name='de_seq',
            field=models.IntegerField(null=True),
        ),
    ]
