# Generated by Django 4.0.4 on 2022-05-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0002_dbupdatechk'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbupdatechk',
            name='duc_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
