# Generated by Django 4.0.4 on 2022-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0003_alter_uploaddb_de_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddb',
            name='de_seq',
        ),
        migrations.AddField(
            model_name='uploaddb',
            name='db_divdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
