# Generated by Django 4.0.4 on 2022-05-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0003_dbupdatechk_duc_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DbUpdateChk',
        ),
    ]
