# Generated by Django 4.0.4 on 2022-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0004_remove_uploaddb_de_seq_uploaddb_db_divdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddb',
            name='db_divdate',
            field=models.DateTimeField(null=True),
        ),
    ]
