# Generated by Django 4.0.4 on 2022-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0005_chkdbreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmemo',
            name='dm_memos',
            field=models.CharField(default='', max_length=2550),
        ),
    ]
