# Generated by Django 4.0.4 on 2022-05-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanageapp', '0005_alter_uploaddb_db_divdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddb',
            name='db_divdate',
        ),
    ]
